apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  namespace: leumi
  labels:
    app: eks-sample-linux-app
spec:
  selector:
    app: eks-sample-linux-app
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer
